import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Language = 'en' | 'zh'

const en = {
  'journal.recordsDescription': 'Save reflections and ideas as independent records, then reopen and edit them whenever needed.',
  'nav.taskNotes': 'Task Notes',
  'journal.newEntry': 'New journal entry', 'journal.entries': 'Journal entries', 'journal.openEntry': 'Open journal entry', 'journal.openThought': 'Open thought', 'journal.editEntry': 'Edit journal entry', 'journal.editThought': 'Edit thought', 'journal.created': 'Created {time}', 'journal.lastEdited': 'Last edited {time}', 'journal.neverEdited': 'Not edited yet', 'journal.editHistory': 'Edit history', 'journal.editedCount': '{count} edits', 'journal.saveChanges': 'Save changes', 'journal.deleteEntry': 'Delete entry', 'journal.deleteThought': 'Delete thought', 'journal.deleteEntryConfirm': 'Delete this journal entry permanently?', 'journal.deleteThoughtConfirm': 'Delete “{title}” permanently?', 'journal.date': 'Entry date', 'journal.entrySaved': 'Journal entry saved.', 'journal.changesSaved': 'Changes saved.', 'journal.noEntries': 'No journal entries yet', 'journal.noEntriesDescription': 'Write freely and save the first entry when you are ready.',
  'taskNotes.eyebrow': 'Low-friction planning', 'taskNotes.title': 'Task Notes', 'taskNotes.description': 'A free-form space to unload, sort and rethink tasks without filling in any fields.', 'taskNotes.label': 'Your task scratchpad', 'taskNotes.placeholder': 'Write anything here—unfinished tasks, reminders, rough priorities, or the next thing to do…', 'taskNotes.saved': 'Saved locally', 'taskNotes.saving': 'Saving…', 'taskNotes.lastSaved': 'Last saved {time}', 'taskNotes.empty': 'Start typing. Your notes save automatically.',
  'goals.deleteMetricEntry': 'Delete metric entry', 'goals.deleteMetricConfirm': 'Delete the {date} entry ({value})? This will update the goal’s current metric and related summaries.', 'goals.metricDeleted': 'Metric entry deleted.',
  'common.today': 'Today', 'common.tomorrow': 'Tomorrow',
  'dashboard.completedCount': '{done}/{total} completed', 'dashboard.clearDayDesc': 'Add one task that meaningfully moves a goal forward.', 'dashboard.addTodayFocus': "Add today's focus", 'dashboard.upcomingDeadlines': 'Upcoming deadlines', 'dashboard.next7Days': 'Next 7 days', 'dashboard.noDeadlinesDesc': 'Nothing is due in the next seven days.', 'dashboard.viewAll': 'View all', 'dashboard.timelineStarts': 'Your timeline starts here', 'dashboard.timelineStartsDesc': 'Capture a meaningful outcome when it happens.', 'dashboard.weeklyReviewDesc': 'Turn activity into learning in five focused minutes.', 'dashboard.openThisWeek': 'Open this week',
  'app.tagline': 'Personal growth system',
  'nav.dashboard': 'Dashboard', 'nav.calendar': 'Calendar', 'nav.goals': 'Goals', 'nav.achievements': 'Achievements', 'nav.journal': 'Journal', 'nav.review': 'Weekly Review', 'nav.quickAdd': 'Quick Add', 'nav.settings': 'Settings',
  'language.toChinese': 'Switch to Chinese', 'language.toEnglish': '切换到英文',
  'common.add': 'Add', 'common.edit': 'Edit', 'common.delete': 'Delete', 'common.cancel': 'Cancel', 'common.save': 'Save', 'common.saving': 'Saving…', 'common.loading': 'Loading view…', 'common.noGoal': 'No goal', 'common.noProject': 'No project', 'common.allGoals': 'All goals', 'common.allCategories': 'All categories', 'common.viewAll': 'View all', 'common.target': 'Target', 'common.started': 'Started', 'common.entries': '{count} entries', 'common.goalsCount': '{count} goals',
  'capture.task': 'Task', 'capture.thought': 'Thought', 'capture.achievement': 'Achievement', 'capture.milestone': 'Milestone', 'capture.quick': 'Quick capture · {type}', 'capture.edit': 'Edit {type}', 'capture.description': 'Save the essential information now. Add detail only when it helps.', 'capture.title': 'Title', 'capture.titleTaskPlaceholder': 'What needs to move forward?', 'capture.titlePlaceholder': 'Name this {type}', 'capture.descriptionLabel': 'Description', 'capture.thoughtLabel': 'Thought', 'capture.contextPlaceholder': 'Optional context', 'capture.tags': 'Tags', 'capture.tagsHint': 'Separate tags with commas', 'capture.tagsPlaceholder': 'Research, Career', 'capture.goal': 'Goal', 'capture.project': 'Project', 'capture.category': 'Category', 'capture.priority': 'Priority', 'capture.estimate': 'Estimate (min)', 'capture.scheduled': 'Scheduled', 'capture.deadline': 'Deadline', 'capture.date': 'Date', 'capture.deleteTask': 'Delete task', 'capture.deleteMilestone': 'Delete milestone', 'capture.save': 'Save {type}', 'capture.saveChanges': 'Save changes', 'capture.errorTitle': 'Add a title before saving.', 'capture.errorLongTitle': 'Keep the title under 160 characters.', 'capture.errorSave': 'Could not save. Your input has been preserved.',
  'dashboard.eyebrow': '{weekday} · {date}', 'dashboard.greeting': 'Good morning', 'dashboard.description': 'Keep the important things moving. Everything else can wait.', 'dashboard.quickAdd': 'Quick add', 'dashboard.captureSeconds': 'Capture in seconds', 'dashboard.todayFocus': "Today's focus", 'dashboard.completed': '{done}/{total} completed', 'dashboard.addTask': 'Add task', 'dashboard.clearDay': 'A clear day', 'dashboard.clearDayDescription': 'Add one task that meaningfully moves a goal forward.', 'dashboard.addToday': "Add today's focus", 'dashboard.unlinked': 'Unlinked', 'dashboard.unlinkedTask': 'Unlinked task', 'dashboard.upcoming': 'Upcoming deadlines', 'dashboard.nextSeven': 'Next 7 days', 'dashboard.today': 'Today', 'dashboard.tomorrow': 'Tomorrow', 'dashboard.days': '{count} days', 'dashboard.noDeadlines': 'No near deadlines', 'dashboard.noDeadlinesDescription': 'Nothing is due in the next seven days.', 'dashboard.weeklyOverview': 'Weekly overview', 'dashboard.plannedActual': 'Planned / actual', 'dashboard.tasksCompleted': 'Tasks completed', 'dashboard.completionRate': 'Completion rate', 'dashboard.weightChange': 'Weight change', 'dashboard.exercise': 'Exercise', 'dashboard.weightTrend': 'Weight trend', 'dashboard.metricHistory': 'Metric history', 'dashboard.activeGoals': 'Active goals', 'dashboard.recentAchievements': 'Recent achievements', 'dashboard.noAchievements': 'Your timeline starts here', 'dashboard.noAchievementsDescription': 'Capture a meaningful outcome when it happens.', 'dashboard.weeklyReview': 'Weekly review', 'dashboard.reviewDescription': 'Turn activity into learning in five focused minutes.', 'dashboard.openWeek': 'Open this week', 'dashboard.statusFor': 'Status for {title}', 'dashboard.completeTask': 'Complete {title}', 'dashboard.markTodo': 'Mark {title} todo',
  'goals.eyebrow': 'Long-term direction', 'goals.title': 'Goals', 'goals.description': 'Keep the small set of outcomes that deserve consistent attention.', 'goals.new': 'New goal', 'goals.noDescription': 'No description yet.', 'goals.manualProgress': 'Manual progress', 'goals.noActive': 'No active goals', 'goals.noActiveDescription': 'Create one meaningful outcome to give your tasks direction.', 'goals.create': 'Create a goal', 'goals.editGoal': 'Edit goal', 'goals.createGoal': 'Create goal', 'goals.formDescription': 'Define the outcome clearly enough to guide weekly choices.', 'goals.titleLabel': 'Title', 'goals.descriptionLabel': 'Description', 'goals.category': 'Category', 'goals.status': 'Status', 'goals.startDate': 'Start date', 'goals.targetDate': 'Target date', 'goals.progressType': 'Progress type', 'goals.progressPercent': 'Progress (%)', 'goals.start': 'Start', 'goals.current': 'Current', 'goals.target': 'Target', 'goals.unit': 'Unit', 'goals.unitPlaceholder': 'kg, papers, hours…', 'goals.delete': 'Delete', 'goals.deleteConfirm': 'Delete “{title}” and its projects, tasks and metrics? Historical achievements will be kept.', 'goals.save': 'Save goal', 'goals.loading': 'Loading goal…', 'goals.notFound': 'Goal not found', 'goals.notFoundDescription': 'This goal may have been deleted.', 'goals.back': 'Back to goals', 'goals.all': 'All goals', 'goals.addTask': 'Add task', 'goals.progress': 'Progress', 'goals.timeline': 'Timeline', 'goals.openEnded': 'Open ended', 'goals.currentMetric': 'Current metric', 'goals.projects': 'Projects', 'goals.addProject': 'Add project', 'goals.projectTitle': 'Project title', 'goals.noProjects': 'No projects', 'goals.noProjectsDescription': 'Projects turn this goal into a concrete stream of work.', 'goals.tasks': 'Tasks', 'goals.noTasks': 'No tasks', 'goals.noTasksDescription': 'Add the next physical action for this goal.', 'goals.metrics': 'Metrics', 'goals.metricName': 'Metric name, e.g. Weight', 'goals.createMetric': 'Create metric', 'goals.value': 'Value', 'goals.record': 'Record', 'goals.noMetricEntries': 'No metric entries yet.', 'goals.notes': 'Notes', 'goals.notePlaceholder': 'Add a note about this goal', 'goals.noAchievements': 'No achievements yet', 'goals.noAchievementsDescription': 'Record a notable outcome when it happens.', 'goals.noProject': 'No project', 'goals.deleteProject': 'Delete {title}', 'goals.toggleTask': 'Toggle {title}',
  'calendar.eyebrow': 'Time and commitments', 'calendar.title': 'Calendar', 'calendar.description': 'Scheduled work, hard deadlines and meaningful milestones in one view.', 'calendar.legendTask': 'Task', 'calendar.legendDeadline': 'Deadline', 'calendar.legendMilestone': 'Milestone', 'calendar.loading': 'Building your calendar…', 'calendar.duePrefix': 'Due · {title}',
  'achievements.eyebrow': 'Evidence of progress', 'achievements.title': 'Achievements', 'achievements.description': 'Important outcomes that already happened—not another list of routine completions.', 'achievements.add': 'Add achievement', 'achievements.filterGoal': 'Filter by goal', 'achievements.filterCategory': 'Filter by category', 'achievements.noMatch': 'No achievements match', 'achievements.noMatchDescription': 'Capture a milestone, breakthrough or meaningful first.', 'achievements.archivedGoal': 'Archived goal',
  'journal.eyebrow': 'Reflection and ideas', 'journal.title': 'Journal', 'journal.description': 'One daily reflection, plus every thought worth keeping.', 'journal.captureThought': 'Capture thought', 'journal.loading': 'Opening your journal…', 'journal.today': 'Today', 'journal.prompt': 'What is on your mind?', 'journal.placeholder': 'A short reflection is enough…', 'journal.mood': 'Mood', 'journal.energy': 'Energy', 'journal.saved': 'Saved locally', 'journal.save': 'Save journal', 'journal.thoughts': 'Thoughts', 'journal.noThoughts': 'No thoughts captured', 'journal.noThoughtsDescription': 'Save an idea before it disappears.', 'journal.recentEntries': 'Recent entries', 'journal.noReflection': 'No written reflection.', 'journal.rating': 'Mood {mood}/5 · Energy {energy}/5',
  'review.eyebrow': 'Learn from the week', 'review.title': 'Weekly Review', 'review.description': 'Look at the evidence, name the lesson, and choose no more than three next priorities.', 'review.loading': 'Calculating your week…', 'review.stats': 'Weekly stats', 'review.englishTime': 'English time', 'review.researchTime': 'Research time', 'review.exerciseTime': 'Exercise time', 'review.planned': 'planned {time}', 'review.wentWell': 'What went well?', 'review.didntGoWell': "What didn't go well?", 'review.biggestAchievement': 'Biggest achievement', 'review.noLinkedAchievement': 'No linked achievement', 'review.biggestProblem': 'Biggest problem', 'review.nextFocus': "Next week's focus", 'review.maximum': 'Maximum 3', 'review.focusPlaceholder': '{number}. Focus area', 'review.saved': 'Review saved locally', 'review.save': 'Save review', 'review.previous': 'Previous week', 'review.next': 'Next week',
  'settings.eyebrow': 'Local and private', 'settings.title': 'Settings', 'settings.description': 'Your Life OS data stays in this browser. No account, cloud sync or analytics.', 'settings.localData': 'Local data', 'settings.indexedDb': 'IndexedDB storage', 'settings.indexedDbDescription': 'All Goals, Tasks, Metrics, Achievements and Journal entries persist locally.', 'settings.export': 'Export JSON', 'settings.demoData': 'Demo data', 'settings.demoRemoved': 'Demo data is removed', 'settings.demoActive': 'Demo data is active', 'settings.demoDescription': 'Demo records are tagged separately. Removing them never touches personal records, even when titles match.', 'settings.restore': 'Restore demo', 'settings.remove': 'Remove demo', 'settings.removeConfirm': 'Remove only the tagged demo records? Your own data will be kept.', 'settings.note': 'Life OS V1 intentionally does not include AI, external integrations, cloud sync, collaboration or advanced notifications.',
} as const

type TranslationKey = keyof typeof en

const zh: Record<TranslationKey, string> = {
  'journal.recordsDescription': '把日志和想法保存为独立记录，之后可以随时打开和编辑。',
  'nav.taskNotes': '任务梳理',
  'journal.newEntry': '新建日志', 'journal.entries': '日志记录', 'journal.openEntry': '打开日志记录', 'journal.openThought': '打开想法', 'journal.editEntry': '编辑日志', 'journal.editThought': '编辑想法', 'journal.created': '创建于 {time}', 'journal.lastEdited': '最近编辑于 {time}', 'journal.neverEdited': '尚未编辑', 'journal.editHistory': '编辑时间记录', 'journal.editedCount': '编辑 {count} 次', 'journal.saveChanges': '保存修改', 'journal.deleteEntry': '删除日志', 'journal.deleteThought': '删除想法', 'journal.deleteEntryConfirm': '确定永久删除这条日志吗？', 'journal.deleteThoughtConfirm': '确定永久删除“{title}”吗？', 'journal.date': '日志日期', 'journal.entrySaved': '日志已保存。', 'journal.changesSaved': '修改已保存。', 'journal.noEntries': '还没有日志记录', 'journal.noEntriesDescription': '先自由写下来，准备好后保存第一条日志。',
  'taskNotes.eyebrow': '低摩擦规划', 'taskNotes.title': '任务梳理', 'taskNotes.description': '不用填写任何选项，随手卸下、整理和重新思考所有任务。', 'taskNotes.label': '任务备忘录', 'taskNotes.placeholder': '随意写下未完成任务、提醒、粗略优先级，或下一步要做的事情……', 'taskNotes.saved': '已保存到本地', 'taskNotes.saving': '保存中…', 'taskNotes.lastSaved': '最近保存于 {time}', 'taskNotes.empty': '直接开始输入，内容会自动保存。',
  'goals.deleteMetricEntry': '删除指标记录', 'goals.deleteMetricConfirm': '确定删除 {date} 的记录（{value}）吗？目标当前值和相关统计将随之更新。', 'goals.metricDeleted': '指标记录已删除。',
  'common.today': '今天', 'common.tomorrow': '明天',
  'dashboard.completedCount': '已完成 {done}/{total}', 'dashboard.clearDayDesc': '添加一项真正能推进目标的任务。', 'dashboard.addTodayFocus': '添加今日重点', 'dashboard.upcomingDeadlines': '即将到期', 'dashboard.next7Days': '未来 7 天', 'dashboard.noDeadlinesDesc': '未来七天内没有任务到期。', 'dashboard.viewAll': '查看全部', 'dashboard.timelineStarts': '从这里开始记录成果', 'dashboard.timelineStartsDesc': '当重要进展发生时，把它记录下来。', 'dashboard.weeklyReviewDesc': '用五分钟把一周的行动转化为经验。', 'dashboard.openThisWeek': '打开本周复盘',
  'app.tagline': '个人成长管理系统',
  'nav.dashboard': '仪表盘', 'nav.calendar': '日历', 'nav.goals': '目标', 'nav.achievements': '成就', 'nav.journal': '日志', 'nav.review': '每周复盘', 'nav.quickAdd': '快速添加', 'nav.settings': '设置',
  'language.toChinese': '切换到中文', 'language.toEnglish': 'Switch to English',
  'common.add': '添加', 'common.edit': '编辑', 'common.delete': '删除', 'common.cancel': '取消', 'common.save': '保存', 'common.saving': '保存中…', 'common.loading': '正在加载页面…', 'common.noGoal': '未关联目标', 'common.noProject': '未关联项目', 'common.allGoals': '全部目标', 'common.allCategories': '全部分类', 'common.viewAll': '查看全部', 'common.target': '目标', 'common.started': '开始于', 'common.entries': '{count} 条记录', 'common.goalsCount': '{count} 个目标',
  'capture.task': '任务', 'capture.thought': '想法', 'capture.achievement': '成就', 'capture.milestone': '里程碑', 'capture.quick': '快速记录 · {type}', 'capture.edit': '编辑{type}', 'capture.description': '先保存最重要的信息，需要时再补充细节。', 'capture.title': '标题', 'capture.titleTaskPlaceholder': '下一步要推进什么？', 'capture.titlePlaceholder': '为这个{type}命名', 'capture.descriptionLabel': '描述', 'capture.thoughtLabel': '想法内容', 'capture.contextPlaceholder': '可选背景信息', 'capture.tags': '标签', 'capture.tagsHint': '使用逗号分隔标签', 'capture.tagsPlaceholder': '科研，职业', 'capture.goal': '目标', 'capture.project': '项目', 'capture.category': '分类', 'capture.priority': '优先级', 'capture.estimate': '预计用时（分钟）', 'capture.scheduled': '安排日期', 'capture.deadline': '截止日期', 'capture.date': '日期', 'capture.deleteTask': '删除任务', 'capture.deleteMilestone': '删除里程碑', 'capture.save': '保存{type}', 'capture.saveChanges': '保存修改', 'capture.errorTitle': '保存前请填写标题。', 'capture.errorLongTitle': '标题不能超过 160 个字符。', 'capture.errorSave': '保存失败，你填写的内容已保留。',
  'dashboard.eyebrow': '{date} · {weekday}', 'dashboard.greeting': '早上好', 'dashboard.description': '持续推进重要的事，其他事情可以稍后处理。', 'dashboard.quickAdd': '快速添加', 'dashboard.captureSeconds': '几秒钟完成记录', 'dashboard.todayFocus': '今日重点', 'dashboard.completed': '已完成 {done}/{total}', 'dashboard.addTask': '添加任务', 'dashboard.clearDay': '今天还很清爽', 'dashboard.clearDayDescription': '添加一项真正能推进目标的任务。', 'dashboard.addToday': '添加今日重点', 'dashboard.unlinked': '未关联', 'dashboard.unlinkedTask': '未关联任务', 'dashboard.upcoming': '即将到期', 'dashboard.nextSeven': '未来 7 天', 'dashboard.today': '今天', 'dashboard.tomorrow': '明天', 'dashboard.days': '{count} 天', 'dashboard.noDeadlines': '近期没有截止日期', 'dashboard.noDeadlinesDescription': '未来七天内没有任务到期。', 'dashboard.weeklyOverview': '本周概览', 'dashboard.plannedActual': '计划 / 实际', 'dashboard.tasksCompleted': '已完成任务', 'dashboard.completionRate': '完成率', 'dashboard.weightChange': '体重变化', 'dashboard.exercise': '运动', 'dashboard.weightTrend': '体重趋势', 'dashboard.metricHistory': '指标历史', 'dashboard.activeGoals': '进行中的目标', 'dashboard.recentAchievements': '最近成就', 'dashboard.noAchievements': '从这里开始记录成果', 'dashboard.noAchievementsDescription': '当重要进展发生时，把它记录下来。', 'dashboard.weeklyReview': '每周复盘', 'dashboard.reviewDescription': '用五分钟把一周的行动转化为经验。', 'dashboard.openWeek': '打开本周复盘', 'dashboard.statusFor': '{title} 的状态', 'dashboard.completeTask': '完成 {title}', 'dashboard.markTodo': '将 {title} 改为待办',
  'goals.eyebrow': '长期方向', 'goals.title': '目标', 'goals.description': '只保留那些真正值得持续投入的关键结果。', 'goals.new': '新建目标', 'goals.noDescription': '还没有描述。', 'goals.manualProgress': '手动进度', 'goals.noActive': '没有进行中的目标', 'goals.noActiveDescription': '创建一个有意义的结果，为每天的任务提供方向。', 'goals.create': '创建目标', 'goals.editGoal': '编辑目标', 'goals.createGoal': '创建目标', 'goals.formDescription': '把结果定义清楚，让它能够指导每周的选择。', 'goals.titleLabel': '标题', 'goals.descriptionLabel': '描述', 'goals.category': '分类', 'goals.status': '状态', 'goals.startDate': '开始日期', 'goals.targetDate': '目标日期', 'goals.progressType': '进度类型', 'goals.progressPercent': '进度（%）', 'goals.start': '起点', 'goals.current': '当前', 'goals.target': '目标', 'goals.unit': '单位', 'goals.unitPlaceholder': 'kg、论文、小时…', 'goals.delete': '删除', 'goals.deleteConfirm': '确定删除“{title}”及其项目、任务和指标吗？历史成就会被保留。', 'goals.save': '保存目标', 'goals.loading': '正在加载目标…', 'goals.notFound': '未找到目标', 'goals.notFoundDescription': '这个目标可能已被删除。', 'goals.back': '返回目标列表', 'goals.all': '全部目标', 'goals.addTask': '添加任务', 'goals.progress': '进度', 'goals.timeline': '时间线', 'goals.openEnded': '无固定期限', 'goals.currentMetric': '当前指标', 'goals.projects': '项目', 'goals.addProject': '添加项目', 'goals.projectTitle': '项目标题', 'goals.noProjects': '还没有项目', 'goals.noProjectsDescription': '项目把长期目标转化为具体工作流。', 'goals.tasks': '任务', 'goals.noTasks': '还没有任务', 'goals.noTasksDescription': '添加一个可以立即执行的下一步行动。', 'goals.metrics': '指标', 'goals.metricName': '指标名称，例如体重', 'goals.createMetric': '创建指标', 'goals.value': '数值', 'goals.record': '记录', 'goals.noMetricEntries': '还没有指标记录。', 'goals.notes': '备注', 'goals.notePlaceholder': '添加与这个目标有关的备注', 'goals.noAchievements': '还没有成就', 'goals.noAchievementsDescription': '当重要成果发生时，把它记录下来。', 'goals.noProject': '未关联项目', 'goals.deleteProject': '删除 {title}', 'goals.toggleTask': '切换 {title} 的完成状态',
  'calendar.eyebrow': '时间与承诺', 'calendar.title': '日历', 'calendar.description': '在同一个视图中查看计划任务、明确截止日期和重要里程碑。', 'calendar.legendTask': '任务', 'calendar.legendDeadline': '截止日期', 'calendar.legendMilestone': '里程碑', 'calendar.loading': '正在生成日历…', 'calendar.duePrefix': '截止 · {title}',
  'achievements.eyebrow': '进步的证据', 'achievements.title': '成就', 'achievements.description': '记录已经发生的重要成果，而不是重复列出日常完成事项。', 'achievements.add': '添加成就', 'achievements.filterGoal': '按目标筛选', 'achievements.filterCategory': '按分类筛选', 'achievements.noMatch': '没有符合条件的成就', 'achievements.noMatchDescription': '记录一个里程碑、突破或有意义的第一次。', 'achievements.archivedGoal': '已归档目标',
  'journal.eyebrow': '反思与想法', 'journal.title': '日志', 'journal.description': '每天一篇主要记录，并保存所有值得留下的想法。', 'journal.captureThought': '记录想法', 'journal.loading': '正在打开日志…', 'journal.today': '今天', 'journal.prompt': '你现在在想什么？', 'journal.placeholder': '简短记录几句就足够了…', 'journal.mood': '心情', 'journal.energy': '精力', 'journal.saved': '已保存到本地', 'journal.save': '保存日志', 'journal.thoughts': '想法', 'journal.noThoughts': '还没有记录想法', 'journal.noThoughtsDescription': '在灵感消失前把它保存下来。', 'journal.recentEntries': '最近日志', 'journal.noReflection': '没有文字记录。', 'journal.rating': '心情 {mood}/5 · 精力 {energy}/5',
  'review.eyebrow': '从一周中学习', 'review.title': '每周复盘', 'review.description': '查看真实数据，总结经验，并选择不超过三个下周重点。', 'review.loading': '正在计算本周数据…', 'review.stats': '本周统计', 'review.englishTime': '英语时间', 'review.researchTime': '科研时间', 'review.exerciseTime': '运动时间', 'review.planned': '计划 {time}', 'review.wentWell': '哪些事情做得好？', 'review.didntGoWell': '哪些事情不顺利？', 'review.biggestAchievement': '本周最大成就', 'review.noLinkedAchievement': '不关联成就', 'review.biggestProblem': '最大问题', 'review.nextFocus': '下周重点', 'review.maximum': '最多 3 项', 'review.focusPlaceholder': '{number}. 重点事项', 'review.saved': '复盘已保存到本地', 'review.save': '保存复盘', 'review.previous': '上一周', 'review.next': '下一周',
  'settings.eyebrow': '本地且私密', 'settings.title': '设置', 'settings.description': 'Life OS 数据只保存在当前浏览器中，不需要账号、云同步或分析服务。', 'settings.localData': '本地数据', 'settings.indexedDb': 'IndexedDB 存储', 'settings.indexedDbDescription': '所有目标、任务、指标、成就和日志都会持久保存在本地。', 'settings.export': '导出 JSON', 'settings.demoData': '演示数据', 'settings.demoRemoved': '演示数据已移除', 'settings.demoActive': '演示数据已启用', 'settings.demoDescription': '演示记录有独立标记，删除时绝不会影响个人数据，即使标题相同。', 'settings.restore': '恢复演示数据', 'settings.remove': '移除演示数据', 'settings.removeConfirm': '只移除带有演示标记的记录吗？你的个人数据会保留。', 'settings.note': 'Life OS V1 有意不包含 AI、外部集成、云同步、协作或高级通知。',
}

const valueLabels: Record<Language, Record<string, string>> = {
  en: {},
  zh: { Health: '健康', English: '英语', Research: '科研', Academic: '学业', Career: '职业', Life: '生活', Other: '其他', Active: '进行中', Paused: '已暂停', Completed: '已完成', Archived: '已归档', Manual: '手动', Metric: '指标', Todo: '待办', 'In Progress': '进行中', Done: '已完成', Skipped: '已跳过', Low: '低', Medium: '中', High: '高', None: '无', Daily: '每天', Weekly: '每周' },
}

interface I18nContextValue {
  language: Language
  toggleLanguage: () => void
  t: (key: TranslationKey, variables?: Record<string, string | number>) => string
  label: (value: string) => string
}

const I18nContext = createContext<I18nContextValue | null>(null)

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => localStorage.getItem('life-os-language') === 'zh' ? 'zh' : 'en')
  useEffect(() => { localStorage.setItem('life-os-language', language); document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en' }, [language])
  const value = useMemo<I18nContextValue>(() => ({
    language,
    toggleLanguage: () => setLanguage((current) => current === 'en' ? 'zh' : 'en'),
    t: (key, variables = {}) => Object.entries(variables).reduce((text, [name, replacement]) => text.replaceAll(`{${name}}`, String(replacement)), (language === 'zh' ? zh[key] : en[key])),
    label: (raw) => valueLabels[language][raw] ?? raw,
  }), [language])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n() {
  const context = useContext(I18nContext)
  if (!context) throw new Error('useI18n must be used inside I18nProvider')
  return context
}
